/* eslint-disable no-fallthrough */
import { BigInteger } from "jsbn";
import { SRPConfig } from "../config";
import { SRPParameters } from "../parameters";
import { SRPRoutines } from "../routines";
import { SRPClientSession } from "../session-client";
import { SRPServerSession } from "../session-server";
import {
  bigIntegerToWordArray,
  createVerifierAndSalt,
  generateRandomString,
  stringToWordArray,
  wordArrayToBigInteger,
} from "../utils";
import { test } from "./tests";

const testParameters = new SRPParameters();
class SRP6aRoutines extends SRPRoutines {
  public computeX(_I: string, s: BigInteger, P: string): BigInteger {
    return wordArrayToBigInteger(
      this.hash(
        bigIntegerToWordArray(s),
        this.hash(stringToWordArray(`${_I}:${P}`)),
      ),
    );
  }
}
const TestConfig = new SRPConfig(testParameters, (p) => new SRP6aRoutines(p));

test("#SRP6aSession success", (t) => {
  t.plan(1);

  const testUsername = generateRandomString(10);
  const testPassword = generateRandomString(15);

  // Sign up
  // salt and verifier are generated by client during signup
  // verifier is read from server storage for server.step1
  const { s: salt, v: verifier } = createVerifierAndSalt(
    TestConfig,
    testUsername,
    testPassword,
  );

  // Sign in
  const clientSession = new SRPClientSession(TestConfig);
  clientSession.step1(testUsername, testPassword);

  const serverSession = new SRPServerSession(TestConfig);
  // server gets identifier from client, salt+verifier from db (from signup)
  const B = serverSession.step1(testUsername, salt, verifier);

  // client gets challenge B from server step1 and sends prove M1 to server
  const { A, M1 } = clientSession.step2(salt, B);

  // servers checks client prove M1 and sends server prove M2 to client
  const M2 = serverSession.step2(A, M1);

  // client ensures server identity
  clientSession.step3(M2);
  t.pass(`user:${testUsername}, password:${testPassword}, salt: ${salt}`);
});

test("#SRP6aSession config mismatch", (t) => {
  t.plan(1);

  const testUsername = "testUser";
  const testPassword = "testPassword";

  const defaultConfig = new SRPConfig(
    testParameters,
    (p) => new SRPRoutines(p),
  );

  // Sign up
  const { s: salt, v: verifier } = createVerifierAndSalt(
    TestConfig,
    testUsername,
    testPassword,
  );

  // Sign in
  const clientSession = new SRPClientSession(defaultConfig);
  clientSession.step1(testUsername, testPassword);

  // server gets identifier from client, salt+verifier from db (from signup)
  const serverSession = new SRPServerSession(TestConfig);
  const B = serverSession.step1(testUsername, salt, verifier);

  // client gets challenge B from server step1 and sends prove M1 to server
  const { A, M1 } = clientSession.step2(salt, B);

  t.throws(() => serverSession.step2(A, M1), /bad client credentials/i);
});
