name: Pages

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build esm
        run: yarn build:esm

      - name: Coverage report
        run: yarn coverage:report

      - name: Make pages dir
        run: |
          mkdir pages
          cp -R dist/. pages/dist
          cp -R demo/. pages/demo
          cp -R reports/unit/. pages/coverage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Coverage number
        run: |
          echo "Running tests with coverage..."
          COVERAGE=$(yarn coverage:number)
          echo "Overall coverage: ${COVERAGE}%"
          echo "COVERAGE=${COVERAGE}" >> $GITHUB_ENV

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6d88c7cb89cc67292dc093e5d7bcede3
          filename: tssrp6a-coverage-badge.json
          label: Test coverage
          message: "${{ env.COVERAGE }}%"
          color: green

